[package]
name = "bb8-redis"
version = "0.8.0"
authors = [
    "Dirkjan Ochtman <dirkjan@ochtman.nl>",
    "Daniel Smith <smith.daniel.br@gmail.com>",
    "Kyle Huey <khuey@kylehuey.com>"
]
description = "Full-featured async (tokio-based) redis connection pool (like r2d2)"
license = "MIT"
repository = "https://github.com/khuey/bb8"
edition = "2018"

[dependencies]
async-trait = "0.1"
bb8 = { version = "0.7", path = "../bb8" }
# redis = { version = "0.19", default-features = false, features = ["tokio-comp"] }
redis = { git = "https://github.com/mitsuhiko/redis-rs", branch = "master", default-features = false, features = ["tokio-comp"]  }

[dev-dependencies]
futures-util = "0.3.2"
tokio = { version = "1.0.0", features = ["macros", "rt-multi-thread"] }
